[package]
name = "input_map"
version = "0.1.0"
authors = ["George Burton <burtonageo@gmail.com>"]
repository = "https://github.com/burtonageo/input-map"
readme = "./Readme.md"
keywords = ["Input mapping", "Rebind", "Mouse reverse"]
license = "MIT"

[dependencies]
pistoncore-input = "0.4.0"
piston_window = "0.14.0"
piston-viewport = "0.1.0"
