[package]
name = "rebind"
version = "0.1.0"
authors = ["George Burton <burtonageo@gmail.com>"]
repository = "https://github.com/burtonageo/input-map"
readme = "./Readme.md"
keywords = ["Input mapping", "Rebind", "Mouse reverse"]
license = "MIT"

[dependencies]
itertools = "^0.3.0"
pistoncore-input = "^0.5.0"
pistoncore-window = "^0.9.0"
piston-viewport = "^0.1.0"
rustc-serialize = "0.3"

# Needed for doc comments
[dev-dependencies]
piston = "0.10.0"
pistoncore-glutin_window = "0.12"
rebind = {path = "./"}